---
driver:
  name: gce
  project: cryptotracker-4
  zone: europe-west2-c
  email: mogpeat@gmail.com
  tags:
    - test-kitchen
    - all
  service_account_scopes:
    - compute

provisioner:
  name: chef_zero
  
verifier:
  name: inspec

platforms:
  - name: windows-2016
    driver:
      image_project: windows-cloud
      #image_name: windows-server-2016-dc-v20181113
      image_family: windows-2016
      machine_type: n1-standard-4
      disk_size: 100

transport:
  username: chefuser

suites:
  - name: default
    run_list:
      - recipe[morgan1::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
